### ISSUE TITLE
Produce: Add support for message key

### ISSUE THREAD

**Issue by Svenskapojkarna** [FrendsPlatform/Frends.Kafka#13]
A request has arrived for a feature where you can set the key of the message in Kafka standard message.

Implementation proposal:
![image](https://github.com/FrendsPlatform/Frends.Kafka/assets/36008914/46804149-5f1c-4c06-bd1d-8f5048ea8fca)

This value can be null or empty if it is not provided.

**Comment by ttossavainen** [comment]
merged
